### Register
POST http://localhost:8080/auth/register
Content-Type: application/x-www-form-urlencoded

email=admin@mail.com&password=admin123&username=admin&phone=082131213511


### Login
POST  /auth/login HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "email" : "admin@mail.com",
    "password": "admin123"
}

### GET SEARCH USER
GET /users?search[email]=mail HTTP/1.1
Host: localhost:8080
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3ODQ3OTgyMTcsImlhdCI6MTc4NDc5NzMxN30.m7u-qbxclOOxqWyr-_S175weERsmQqgqJCLKFO17aJM


### GET USER
GET /users HTTP/1.1
Host: localhost:8080
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3ODQ3OTk0ODgsImlhdCI6MTc4NDc5ODU4OH0.UOOaVu86ffkmb_reKeujT8o6Zy4MMW22unNyUWkyXOc

### GET BY ID
GET /users/1 HTTP/1.1
Host: localhost:8080
Content-Type: application/x-www-form-urlencoded


### CREATE USER
POST  /users HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "email" : "shidiq@mail.com",
    "password": "shidiq123",
    "username": "shidiq",
    "phone": "081322768862"
}

### UPDATE USER
PATCH /user/1 HTTP/1.1
Host: localhost:8080
Content-Type: application/x-www-form-urlencoded

### DELETE USER
DELETE /user/4 HTTP/1.1
Host: localhost:8080
Authorization: "hello"

###
POST /auth/refresh HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3ODQ5OTk3ODcsImlhdCI6MTc4NDc0MDU4N30.sCKBmpwnjz705ore24EGoh6Jo1VKxpteGlHRkNH2q-8"
}

